---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-env
  namespace: gitea
  labels:
    app: gitea
data:
  APP_NAME: "Gitea"
  USER_UID: "1000"
  USER_GID: "1000"
  ROOT_URL: "https://git.thejimnicholson.com"
  HTTP_PORT: "3000"
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: gitea-db-rw:5432
  GITEA__database__NAME: gitea-db

