---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  strategy:
    #type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - image: gitea/gitea:1.21.10
        name: gitea
        # command: ['sh','-c','echo "Container active" ; sleep 3600000']
        envFrom:
          - configMapRef:
              name: gitea-env
        env:
          - name: GITEA__database__USER
            valueFrom:
              secretKeyRef:
                name: gitea-db-app
                key: user
          - name: GITEA__database__PASSWD
            valueFrom:
              secretKeyRef:
                name: gitea-db-app
                key: password
        ports:
        - containerPort: 3000
          name: gitea
        volumeMounts:
        - name: gitea-storage-nfs
          mountPath: /data
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
      volumes:
      - name: gitea-storage-nfs
        persistentVolumeClaim:
          claimName: gitea-storage-nfs