apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
secretGenerator:
- literals:
  - pg_password=some1pass5here9
  name: gitea-secrets
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
resources:
- namespace.yaml
- storage.yaml
- configuration.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
