apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
secretGenerator:
- literals:
  - pg_username=postgres
  - pg_password=some1pass5here9
  name: gitea-secrets
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
resources:
- namespace.yaml
- 01-postgresql.yaml
- 02-storage.yaml
- configuration.yaml
- gitea-deployment.yaml
- gitea-service.yaml
- ingress.yaml
