apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
# secretGenerator:
# - literals:
#   - pg_password=some1pass5here9
#   name: gitea-secrets
# generatorOptions:
#   disableNameSuffixHash: true
#   labels:
#     type: generated
resources:
- namespace.yaml
- secrets.yaml
- storage.yaml
- configuration.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- gitea-deployment.yaml
- gitea-service.yaml
- ingress.yaml
