apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitea-secrets
  namespace: gitea
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: pg_password
data:
  pg_username: cG9zdGdyZXM=